import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

const font = Inter({ subsets: ["latin"], weight: ['400', '500', '600', '700'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      baseTheme: dark,
      elements: {
        // cardBox: {
        //   boxShadow: "none",
        // },
        formButtonPrimary: {
          backgroundColor: "#76fa77",
          color: "black",
          boxShadow: "none !important",
          padding: "10px",
          fontSize: "14px",
          "&:hover": {
            backgroundColor: "#76fa77e6"
          }
        },
        buttonArrowIcon: {
          display: "none"
        },
        input: {
          padding: "10px",
          fontSize: "14px",
          backgroundColor: "#18181d",
        },
        button: {
          padding: "10px",
          fontSize: "14px",
        },
        footer: {
          background: "transparent",
        }
      },
      variables: {
        colorText: "#fafafa",
        colorBackground: "black",

      }
    }}>
      <html lang="en">
        <body className={font.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
